language: ruby

cache:
  - bundler

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.0
  - gemfiles/Gemfile-rails.4.1
  - gemfiles/Gemfile-rails.4.2
  - gemfiles/Gemfile-rails.5.0

sudo: false

before_install: gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
