language: ruby

cache:
  - bundler

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.0
  - gemfiles/Gemfile-rails.4.1
  - gemfiles/Gemfile-rails.4.2
  - gemfiles/Gemfile-rails.5.0.0.beta3

sudo: false

before_install: gem install bundler -v 1.11.2

matrix:
  allow_failures:
    - rvm: ruby-head
